CREATE DATABASE IF NOT EXISTS ecomerce;
USE ecomerce;


CREATE TABLE IF NOT EXISTS CLIENTE (
    ID_CLIENTE INTEGER AUTO_INCREMENT PRIMARY KEY, 
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    SENHA VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ENDERECO (
    CEP VARCHAR(10) NOT NULL,
    RUA VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    NUMERO_CASA INTEGER NOT NULL,
    CLINT_ID INTEGER NOT NULL
    
);
ALTER TABLE ENDERECO
	ADD CONSTRAINT FK_CLIENT_END FOREIGN KEY (CLINT_ID) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID_PRODUTO INTEGER AUTO_INCREMENT PRIMARY KEY, 
    VALOR_PROD DECIMAL(10, 2) NOT NULL, 
    QTD_ESTOQUE INTEGER NOT NULL,
    COR VARCHAR(50),
    TAMANHO VARCHAR(50),
    MARCA VARCHAR(100),
    TIPO_TECIDO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PEDIDO (
    ID_COMPRA INTEGER AUTO_INCREMENT PRIMARY KEY, 
    PRODUTO_ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    FORMA_PAGAMENTO VARCHAR(50), 
    STATS VARCHAR(50)

);
ALTER TABLE PEDIDO
	ADD CONSTRAINT FK_PROD_PED FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE RESTRICT,
    ADD CONSTRAINT FK_CLIENT_PED FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE RESTRICT; 

CREATE TABLE IF NOT EXISTS FEEDBACK 
(
    CLI_ID INTEGER NOT NULL,
    PROD_ID INTEGER NOT NULL,
    DESCRICAO_AVALIA TEXT, 
    PRIMARY KEY (CLI_ID, PROD_ID)
     
);
ALTER TABLE FEEDBACK 
	ADD CONSTRAINT FK_CLIENT_FEED FOREIGN KEY (CLI_ID) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE RESTRICT,
    ADD CONSTRAINT FK_PROD_FEED FOREIGN KEY (PROD_ID) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS TELEFONE (
    C_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TELEFONE VARCHAR(20),
    CELULAR VARCHAR(20)
);
ALTER TABLE TELEFONE
ADD CONSTRAINT FK_CLIENT_TEL FOREIGN KEY (C_ID) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE RESTRICT;


INSERT INTO CLIENTE (NOME, EMAIL, CPF, SENHA) VALUES
('João Silva', 'joao.silva@email.com', '123.456.789-00', 'senha123'),
('Maria Oliveira', 'maria.oliveira@email.com', '987.654.321-00', 'senha456'),
('Pedro Santos', 'pedro.santos@email.com', '111.222.333-44', 'senha789');

INSERT INTO ENDERECO (CEP, RUA, BAIRRO, NUMERO_CASA, CLINT_ID) VALUES
('12345-678', 'Rua das Flores', 'Jardim das Rosas', 10, 1),
('87654-321', 'Avenida Paulista', 'Centro', 123, 2),
('54321-098', 'Rua dos Pinheiros', 'Pinheiros', 45, 3);

INSERT INTO PRODUTO (VALOR_PROD, QTD_ESTOQUE, COR, TAMANHO, MARCA, TIPO_TECIDO) VALUES
(99.99, 50, 'Vermelho', 'M', 'Marca A', 'Algodão'),
(49.99, 100, 'Azul', 'G', 'Marca B', 'Poliéster'),
(29.99, 75, 'Preto', 'P', 'Marca C', 'Linho');

INSERT INTO PEDIDO (PRODUTO_ID, CLIENTE_ID, FORMA_PAGAMENTO, STATS) VALUES
(1, 1, 'Cartão de Crédito', 'Pendente'),
(2, 2, 'Boleto', 'Concluído'),
(3, 3, 'Pix', 'Cancelado');

INSERT INTO FEEDBACK (CLI_ID, PROD_ID, DESCRICAO_AVALIA) VALUES
(1, 1, 'Excelente produto, recomendo!'),
(2, 2, 'Bom custo-benefício, mas poderia ser melhor.'),
(3, 3, 'Não gostei, o produto chegou danificado.');

INSERT INTO TELEFONE (C_ID, TELEFONE, CELULAR) VALUES
(1, '1122334455', '11987654321'),
(2, '2233445566', '21987654321'),
(3, '3344556677', '31987654321');
